behaviors:
  Kart:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 2.0e-3
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 100000
    time_horizon: 512
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 0.1
        gamma: 0.99

      # GAIL
      gail:
        strength: 1.0
        gamma: 0.99
        encoding_size: 128
        demo_path: demos\demonstrations\2
        learning_rate: 3.0e-4
        use_actions: true
        use_vail: false